version: '3.4'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "123"
        ports:
        - "5432:5432"