networks:
  connector:
    driver: bridge
  
volumes: 
  task.connector.tests-data:
  postgres-data:
  pgadmin-data:

services:
  task.connector.tests:
    container_name: task.connector.tests
    build:
      context: .
      dockerfile: tests/Task.Connector.Tests/Dockerfile
    networks: 
      - connector
    volumes:
     - task.connector.tests-data:/var/lib/task.connector.test
    depends_on:
      - postgres.db

  # backup.db:
  #   container_name: backup.db
  #   build:
  #     context: ./DbCreationUtility
  #     dockerfile: Dockerfile
  #   networks:
  #     - connector
  #   depends_on:
  #     - postgres.db
  #   command: [
  #     "dotnet",
  #     "Task.Integration.Data.DbCreationUtility.dll",
  #     "-s",
  #     "server=host.docker.internal;port=5432;database=test_db;username=user;password=12345678",
  #     "-p",
  #     "POSTGRE"
  #   ] 

  postgres.db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: test_db
    ports:
      - "5432:5433"
    networks:
      - connector
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.11
    environment:
      PGADMIN_DEFAULT_EMAIL: "kalyazin.nik@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - connector
