version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: Kolleper
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"