version: '3.9'
services:
  example-service:
    container_name: example-service
    restart: always
    build:
      context: .
      dockerfile: ./Task.Example/Dockerfile
    environment:
      ConnectionStrings: ${CONNECTION_STRING}
    ports:
      - "5100:5100"
    depends_on:
      - taskDb
  
  taskDb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: